# PG Database
#
#   gem install pg
#

development:
  adapter: postgresql
  database: theljwedding-dev
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: theljwedding-test
  pool: 5
  timeout: 5000

cucumber:
  <<: *test